function header() {
	document.write('<header class="header col-lg-12 col-md-12 col-sm-12" id="header">');
	document.write('<h1 class="col-lg-7 col-md-5 col-sm-5"><a href="index.html"><img src="img/m_logo.png" alt="main logo" title="main logo"></a></h1>')
	document.write('	<div class="drawer">')
	document.write('		<nav class="col-lg-5 col-md-5 col-sm-5 gnb" id="gnb">')
	document.write('			<ul>')
	document.write('				<li class="col-lg-3 col-md-3 col-sm-12">')
	document.write('					<a href="sub01_wwa.html">About</a>')
	document.write('					<ul class="gnb_sub">')
	document.write('						<li><a href="sub01_wwa.html">Who we are</a></li>')
	document.write('						<li><a href="sub01_wwd.html">What we do</a></li>')
	document.write('					</ul>')
	document.write('				</li>')
	document.write('				<li class="col-lg-3 col-md-3 col-sm-12">')
	document.write('					<a href="sub02_pocke.html">Services</a>')
	document.write('					<ul class="gnb_sub">')
	document.write('						<li><a href="sub02_pocke.html">Pockestra</a></li>')
	document.write('						<li><a href="sub02_sound.html">Sound production</a></li>')
	document.write('						<li><a href="sub02_video.html">Video production</a></li>')
	document.write('						<li><a href="sub02_develop.html">Development</a></li>')
	document.write('						<li><a href="sub02_portfolio.html">Portfolio</a></li>')
	document.write('					</ul>')
	document.write('				</li>')
	document.write('				<li class="col-lg-3 col-md-3 col-sm-12"><a href="sub03_blog.html">Blog</a></li>')
	document.write('				<li class="col-lg-3 col-md-3 col-sm-12"><a href="sub04_contact.html">Contact</a></li>')
	document.write('			</ul>')
	document.write('		</nav>')
	document.write('	</div>')
	document.write('	<a class="mob-menu-btn">')
	document.write('		<div class="top-bar"></div>')
	document.write('		<div class="middle-bar"></div>')
	document.write('		<div class="bottom-bar"></div>')
	document.write('	</a>')
	document.write('</header>')
}

function footer() {
	document.write('<footer class="footer container">')
	document.write('	<div class="row">')
	document.write('		<ul class="col-lg-2 col-md-2 col-sm-6 col-xs-6">')
	document.write('			<li><a href="sub01_wwa.html">About</a></li>')
	document.write('			<li><a href="sub01_wwa.html">Who we are</a></li>')
	document.write('			<li><a href="sub01_wwd.html">What we do</a></li>')
	document.write('		</ul>')
	document.write('		<ul class="col-lg-2 col-md-2 col-sm-6 col-xs-6">')
	document.write('			<li><a href="sub02_pocke.html">Services</a></li>')
	document.write('			<li><a href="sub02_pocke.html">Pockestra</a></li>')
	document.write('			<li><a href="sub02_sound.html">Sound production</a></li>')
	document.write('			<li><a href="sub02_video.html">Video production</a></li>')
	document.write('			<li><a href="sub02_develop.html">Development</a></li>')
	document.write('			<li><a href="sub02_portfolio.html">Portfolio</a></li>')
	document.write('		</ul>')
	document.write('		<ul class="col-lg-2 col-md-2 col-sm-6 col-xs-6">')
	document.write('			<li><a href="sub03_blog.html">Blog</a></li>')
	document.write('		</ul>')
	document.write('		<ul class="col-lg-2 col-md-2 col-sm-6 col-xs-6">')
	document.write('			<li><a href="sub04_contact.html">Other</a></li>')
	document.write('			<li><a href="sub04_contact.html">Contact</a></li>')
	document.write('			<li><a href="sub04_Careers.html">Careers</a></li>')
	document.write('		</ul>')
	document.write('	</div>')
	document.write('	<div class="row f_copy">')
	document.write('		<p class="col-lg-12 col-md-12 col-sm-12">Copyright ⓒEast-Control Co., Ltd.  All Rights Reserved.</p>')
	document.write('		<a href="index.html"><img src="img/f_logo.png" alt="logo" title="logo"/></a>')
	document.write('	</div>')
	document.write('</footer>')
}
